### ISSUE TITLE
Disable Newrelic reporting on most everything

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#106]
It's costing us a bunch of money, and we're not using it.

Apps currently reporting to newrelic:
* api.webmaker.org (we want this right now)
* [ ] togetherjs-production
* [ ] thimble-production
* [ ] webmakerorg-production
* [ ] wmlogin-production
* [ ] makeapi-production
* [ ] goggles-production
* [ ] communityit-discourse-production
* [ ] makeapi-staging
* [ ] openbadges-validator-production
* [ ] wmlogin-staging
* [ ] webmakerorg-staging
* [ ] thimble-staging
* [ ] goggles-staging
* [ ] discourse-advocacy
* [ ] webmaker-profile2-production
* [ ] events-api-production
* [ ] adhoctribution-production
* [ ] badgekit-mozilla-production
* [ ] communityit-discourse-guides
* [ ] badgekit-staging
* [ ] webmaker-profile2-staging
* [ ] validator-staging
* [ ] events-api-staging
* [ ] discover-openbadges-production
* [ ] badgekit-mozilla-staging

**Comment by cadecairos** [comment]
cc/ @jbuck @simonwex

**Comment by jbuck** [comment]
To disable this, it looks like we need to disable the agent first. Then we can turn off data collection in the web ui.

**Comment by jbuck** [comment]
Easy way to fix this: rotate old API keys

**Comment by jbuck** [comment]
Okay, we now have 9 applications left:

- api.webmaker.org-loadtesting
- api.webmaker.org-production
- login.webmaker.org-loadtesting
- id.webmaker.org-loadtesting
- id.webmaker.org-production

@flamingspaz Could you work on turning off newrelic for these apps?
- discourse-advocacy
- communityit-discourse-production
- communityit-discourse-guides

@simonwex I can't turn off this app because I don't have access to it on heroku:
- discover-openbadges-production (openbadges-discovery in heroku)

**Comment by flamingspaz** [comment]
Discourse ones no longer report to NR.

**Comment by jbuck** [comment]
@flamingspaz Thanks!

**Comment by jbuck** [comment]
This is basically done as much as we can do now. Thanks everyone!
