### ISSUE TITLE
Unable to push to production

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#145]
When master is pushed to Github, the production site should be updated. That seems to be borked.

When it works, this should reveal a version > 0.0.15
https://teach.mozilla.org/healthcheck/

**Comment by jbuck** [comment]
https://github.com/mozilla/teach.webmaker.org/issues/1129#issuecomment-125667780 is the issue, just need to figure out why

**Comment by jbuck** [comment]
https://github.com/mozilla/teach.webmaker.org/issues/1152 needs to be closed when this is resolved too

Okay, here is what I think happened, and why it v0.0.16 didn't get released properly. For context, refer to the [release docs](https://github.com/mozilla/teach.webmaker.org/blob/c1cba586dd67977768e8f9de2d0eb764d9dc0eb2/RELEASE.md):

- Mavis created [a .16-rc PR](https://github.com/mozilla/teach.webmaker.org/pull/1133) based on develop
- Simon and Mavis added more commits to develop, but didn't update the .16-rc branch with these commits. Check out the [network graph](https://github.com/mozilla/teach.webmaker.org/network), and look at where develop branched from. The confusion continues when Mavis merged the .16-rc branch into master, and then tagged .16 on the develop branch instead of on the .16-rc branch that gets merged to master.

Recommended fixes:
1) Just merge the tag v0.0.16 into master and call it a day
2) Wait until v0.0.17 and ensure that it gets released properly

@simonwex I leave it up to you to decide!
