### ISSUE TITLE
https://netgainpartnership.org/ wordpress site has incorrect domain in config

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#303]
### Details

Links on https://netgainpartnership.org/  link to https://netgainpartner.wpengine.com/grants/ rather than our domain. I suspect this is a setting in the wpengine wp-admin.

### Info & links

Grants link is highlighted here:

![image](https://cloud.githubusercontent.com/assets/25260/14194435/7469cc2c-f763-11e5-8687-aa59ac5acde2.png)

**Comment by alicoding** [comment]
It turns out this is more complicated to edit the theme, and I did some googling and found that the solution to our problem is to update the site url in the settings, but that field is not editable and this article suggest that we change the `wp-config.php` file because it is hard-coded to that. So, I followed the guide https://wpengine.com/support/trouble-editing-home-and-site-url/ and successfully updated that URL and now it's working as expected.
