### ISSUE TITLE
GA tracking ID for London Schedule App

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#357]
### Details

We need a GA tracking ID for the London Schedule app. @mmmavis and I were unsure of the process with @adamlofting's transition. 

While stats aren't critical for London, it would help us demonstrate to MoFo the value of the app for better tracking/understanding of Mozfest and our other events. 

### Info & links

GH Pages: http://mozilla.github.io/mofo-allhands/
London: /2016-london/

I apologize for the last minute request @gideonthomas @cadecairos @alicoding 

https://github.com/mozilla/mofo-allhands/issues/5

**Comment by cadecairos** [comment]
I don't have the necessary permissions to create GA id's (let alone the experience using GA)

@simonwex how should we handle this?

**Comment by xmatthewx** [comment]
I heard rumor that @HPaulJohnson might have the knowledge and the power.

**Comment by HPaulJohnson** [comment]
Hmm, just enough knowledge to be dangerous. I can supply the GA ID's for our existing sites (advocacy, webmaker, learning, etc) but don't have a lot of experience creating new sites/ID's. 

I just checked - and think I can do this (I have the power!) - but not having done this specific thing before I'd love @adamlofting's guidance if possible.

**Comment by adamlofting** [comment]
New GA properties are setup in the account by our friends at MoCo (they own the contract with Google and the account). @HPaulJohnson I suspect you have the power to setup new views under existing properties (i.e. under learning.m.o) but probably not to create new properties.

Details on the process including a link to file a bugzilla bug in the right place are on this page: https://intranet.mozilla.org/Webanalytics/Google_Analytics

In this case, you'll also likely need to put this app on a mozilla domain of some kind, because GA drops cookies at a domain level we wouldn't want to do this on *.github.io which is a domain that can be used by anyone.

**Comment by xmatthewx** [comment]
I guess this all-hands app is an outlier. The app for mozfest or sourcecon or most other events would already have an obvious root domain. It seems like we'll have to skip this.

**Comment by mmmavis** [comment]
All of our schedule apps (SRCCON, MozFest 2015, Hive Buzz, MoFo London All-hands) live on *.github.io . I agree that we wouldn't want GA to drop cookies there.

**Comment by cadecairos** [comment]
I'm going to go ahead and close this up.
