### ISSUE TITLE
Make Pulse prototype work again

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-devops#360]
### Details
This prototype no longer works: 
http://xmatthewx.github.io/network-pulse/

Chris mentioned that its being throttled or something -- can we make it work again? 

cc @xmatthewx @prefontaine

**Comment by cadecairos** [comment]
@acabunoc mentioned that we can avoid using sheetsu altogether since it's just a wrapper around Google sheets. 

It looks like Pulse is simply [pulling in all sheet data](https://github.com/xmatthewx/network-pulse/blob/bc9affcf012d0a311c0d15c8b2edc895f5bd223b/js/pulse.js#L466-L485) so this shouldn't actually bee too hard? (can you confirm this assumption @acabunoc?)

**Comment by acabunoc** [comment]
True! https://github.com/xmatthewx/network-pulse/issues/3

**Comment by cadecairos** [comment]
Since we can leverage Google sheets directly, and won't need a subscription service, I'm going to close this issue in favour of xmatthewx/network-pulse#3
