### ISSUE TITLE
Reconsider where the learning blog should be hosted

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#423]
@hannahkane @xmatthewx 

I recently moved the learning blog off of webmaker.org and onto learning.mozilla.org/blog

For the most part, it worked well, but there is a notable exception to that. Because learning.mozilla.org uses a CloudFront CDN, I had to create rules that proxied requests to `/blog/*` to the learnging blog's wpengine endpoint. What doesn't work with this configuration is logging into the admin page. In order to log in and author posts, you need to visit `webmakerblog.wpengine.com/wp-admin`. This in itself isn't the issue, it's with post previewing. basically, if you want to preview a post, the admin panel tries to send you back to the learning.mozilla.org domain, but because you are not signed into wordpress on that domain, you can not preview posts. A simple hack to work around this is to substitute the mozilla domain in the preview link with the wpengine domain.

I attempted to engage with wpengine support to see if they could figure out a way to make the admin panel work on `learning.mozilla.org/blog` but when they tried to make a change, the entire site became unreachable. I'm honestly not surprised, since using Cloudfront as a proxy, like we are, isn't really its indended use.

If I were to make some recommendations to make this much easier on us, it would be to either use a subdomain, like `learning-blog.mozilla.org` or to engineer a similar solution like the science site is using (fetching post data from the WP JSON API (although that has a whole set of its own problems too, just ask @alanmoo)) 

I also just got a message from WPEngine saying what we're trying to do is "out of their scope of work" and that they "highly suggest a subdomain"

**Comment by xmatthewx** [comment]
Thanks for all the details and options.

Short-term we could set up a redirect from our preferred URL to a subdomain that WP Engine can handle. Do weird URLs matter that much in this day and age? If we added a shortlink plugin so shares can be easy, I'm not sure it matters. Long-term, I defer to @hannahkane whether it makes more since to start fetching things.

**Comment by cadecairos** [comment]
What do you mean by weird urls?

If our prefferred URL is `learning.mozilla.org/blog` The only solution to make that work is probably to mimic what the science site is doing. That will require a significant investment of time to implement I think, I also don't know what issues come with previewing posts in that solution.

**Comment by xmatthewx** [comment]
`learning-blog.mozilla.org` is an odd URL for something that belongs to `learning.mozilla.org`. It's not a common pattern. It's not ideal, but it probably doesn't matter too much if we can have a simple redirect there from `learning.mozilla.org/blog`. A URL we can advertise. I'm _not_ suggesting that we redirect with a wildcard (ex: learning.mozilla.org/blog/this-blog-post). 

We might also enable blog authors or readers via plugin to share posts with a shortlink (bitly or mzlla) so that they don't have to share. Nice to have.

**Comment by cadecairos** [comment]
> I'm not suggesting that we redirect with a wildcard (ex: learning.mozilla.org/blog/this-blog-post).

That's actually pretty easy to do

**Comment by hannahkane** [comment]
cc @simonwex because this actually feels like it's pointing to a larger issue around whether WPEngine should be in our long term plans or not. Feels like this is causing more problems than it might be worth.

For the short/medium-term, I think I'm fine with @xmatthewx's suggestion, though I'm not sure I totally follow. Also wondering if the workaround described in @cadecairos's first comment (authors replace mozilla domain in preview with wpengine domain) is a good-enough workaround for the time being (with no dev work required).

**Comment by simonwex** [comment]
@cadecairos could you file a support ticket with wp-engine and send them this thread? It'd be great to know if they have any suggestions.

**Comment by cadecairos** [comment]
@simonwex I actually am making this recommendation based on a ticket I had open with them. They way we are doing things is "Out of scope of the support team" and they can't help me any further. They recommended a subdomain.

Using a path with wordpress isn't usually an issue, but only when it's using a real reverse proxy. Wordpress doesn't appear to take very kindly to being behind a cloudfront CDN, with a bunch of "helpful" behaviours built in to break things (like automatically re-directing if the Host header's value when it doesn't match the wordpress installation URL)

**Comment by cadecairos** [comment]
@simonwex @xmatthewx @hannahkane 

Any thoughts on what to do here? Do we use a subdomain, do what the science site does, or do we deal with the previewing workaround?

**Comment by alanmoo** [comment]
The approach I wanted to try with the science site might work here too, right? That is, blog.learning.mozilla.org for admin login, and then let learning.mozilla.org/blog just do its thing making WordPress API calls?

**Comment by xmatthewx** [comment]
What's the staff time required to set up /blog to pull in content via API? 

It might be the right longterm approach, but a cheap, short-term fix could serve us better. We could advertise and redirect `learning.mozilla.org/blog` and `/blog/admin` as a quick temp fix. 

I defer to @hannahkane @simonwex on this.

**Comment by alanmoo** [comment]
Oh we're not pulling in the content via API already? If that's the case, my suggestion probably doesn't stand up.

**Comment by hannahkane** [comment]
For some reason, I'm having a lot of trouble following this thread. Is the problem with the "do nothing" option that previewing doesn't work? But there's a workaround—substitute the mozilla domain in the preview link with the wpengine domain?

If that's the case, I'd lean towards keeping it as is, rather than using a subdomain or the extra work of pulling in content via API. But I'd like to get input from people who frequently publish on the blog. Before we do that, I want to confirm that the preview is the only downside to keeping as is.

**Comment by cadecairos** [comment]
It sounds like we're all okay with this the way it is. If that changes, we can start a new thread on the topic.
