### ISSUE TITLE
Donor Data Request for Major Gifts Research

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/mofo-devops#46]
Rebecca Davies, our new interim VP of Fundraising, needs to search our donor database for potential major donors. I need the following queries:

1. Anyone who has given Mozilla a total of $50 or more (as far back as possible); this includes multiple donations totaling $50 or more.
2. Fields needed: All available, including: name, email, complete physical address, donation dates+amounts, etc.

Format: CSV is fine.

**Comment by jbuck** [comment]
Ran some quick numbers:

* Number of donations over $50: ~14k
* Number of donations over $100: ~4k
* Number of donors aggregated by email address who donated over $50: ~8k
* Number of donors aggregated by email address who donated over $100: ~2k

**Comment by jbuck** [comment]
Emailed data to @valianttry and Rebecca.

To generate the data again run the following command:

`\copy (select * from paypal where email in (select email from paypal where status = 'Completed' group by email having sum(amount) > '50'::money) order by email, timestamp) TO '~/donors-over-50.tsv';`

**Comment by jbuck** [comment]
Since I'll probably forget again, the reason we don't have a street address on file is because the paypal api I'm using ( https://developer.paypal.com/docs/classic/api/merchant/GetTransactionDetails_API_Operation_NVP/ ) doesn't provide address information. I suspect another problem with address information is that doing a paypal donation doesn't provide us address information. I think only a credit card transaction processed through BSD gives us address information

**Comment by valianttry** [comment]
@jbuck how difficult would it be to pull the address data we DO have? Anyone who completes the form in BSD should have an address in their record (so, at least 40% of donors who pay with credit card, not PayPal). Can you estimate what it would take to append address data we have?

**Comment by jbuck** [comment]
@valianttry I'm not sure. I guess it depends how we merge the data together... We could access the data using the BSD API or we could do something like export all data from BSD, and then import it into the transaction database. Do you know how to do a BSD data export? That would probably be easier than working with their API...
