### ISSUE TITLE
hivelearningnetworks.org "Error establishing database connection" 

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/mofo-devops#469]
### Details
hivelearningnetworks.org is currently down

It's linked from learning.mozilla.org and is also slated to be linked from the Open Leadership 101 course going live on Teachable next Wednesday

**Comment by cadecairos** [comment]
Got it back up.

This happened due to the database being very poorly named in AWS (it literally had the word "delete" in the title), which led me to believe it wasn't in use. I snapshotted it and deleted it. All I needed to do to fix it was to restore the snapshot and update the WordPress configuration.

**Comment by cadecairos** [comment]
(The database has a name that doesn't imply it's safe to delete now)
