### ISSUE TITLE
Create MoFo VictorOps Account

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#601]
~~The foundation site went down yesterday and it didn't notify us via slack, lets double check the integration.~~

The moco victorops account isn't serving our needs, lets get four seats on a non-profit account with VictorOps. (Full Stack plan)

**Comment by patjouk** [comment]
I don't have access to those integration settings anymore :( Since you've set it up, you will have to check it.

**Comment by cadecairos** [comment]
* check if this was due to a slack outage

**Comment by patjouk** [comment]
I finally reached out to VictorOps support 🏅 
I'll update this issue when I have an answer.

**Comment by patjouk** [comment]
They didn't receive any complaints about that issue. Something is probably broken on our side :(
I described our problem in more details to them: maybe they will have an idea of what might be broken.

Meanwhile, I will ask our slack admin if an integration can have multiple owners: it's a pain to investigate this issue since they changed our slack permissions.

**Comment by patjouk** [comment]
Support checked our transmogrifiers: it should work. They recommended to remove the webhook and to set up a new one. This will take some time because we need service to approve it. The support also recommended we switch to the latest slack integration they offer, which we can't for now because we share an account with MoCo.

@alanmoo I took the opportunity to ask if they have discounts for non-profit and the answer is yes.

**Comment by patjouk** [comment]
I've asked for a new incoming webhook since VictorOps support want us to try to set up the integration again.

**Comment by patjouk** [comment]
Setting up a new integration fixed the issue. @cadecairos can you remove your previous integration?

**Comment by cadecairos** [comment]
@patjouk has reached out to a contact at Splunk about non-profit pricing.

**Comment by patjouk** [comment]
It's done: they will apply the new discount soon. @cadecairos you should have received an invite: can you add the credit card to that new account?

Meanwhile, I'm closing that ticket in favor of a new one dedicated to accounts migrations.
