### ISSUE TITLE
Python minor version updates break pipenv/inv

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mofo-devops#640]
This was tested on pulse-api

I use a mac and use homebrew as my package manager. Occasionally I do `brew upgrade` which updates all packages installed with brew. One of those packages is python 3, which is currently on v3.7.

However, when I try to use pipenv or inv, it seems like it can't figure out python versions. Here are the scenarios with python 3.7 installed:

1. neither `pipenv run ...` or `inv ...` work 
```zsh: /usr/local/bin/pipenv: bad interpreter: /usr/local/opt/python/bin/python3.6: no such file or directory```
2. can't run `pipenv --python 3.7` because it needs python 3.6 to even run that command -- same message as above
3. installing and linking python 3.6 is actually pretty hard with homebrew because it evaluates python 3 to 3.latest and you have to use git shas to get earlier versions.

low priority coz I went with the 3rd option which was difficult, but I have things working and I only need to keep switching back to python 3.6 (there's a brew command for that) when I run `brew upgrade`.

**Comment by cadecairos** [comment]
@patjouk had this exact issue too I think, so she might have the steps to fix it. 

3.7 breaks a lot of things it seems...

**Comment by Pomax** [comment]
@gideonthomas brew should support `brew install python@3.6`, you should not have to figure out git commit sha's

**Comment by gideonthomas** [comment]
perfect thanks @cadecairos, if there are specific steps to fix it, that would help.

@Pomax that isn't valid in brew because `3.6` isn't a valid tap that they have in their repository. Why? No idea...

**Comment by patjouk** [comment]
Yeah, I did the same thing: update brew and realized that I installed 3.7 :D
For your issue, you need to reinstall pipenv and invoke to use 3.7 instead *BUT*, keeping 3.6 is better in our situation: our projects use python 3.6, as written in our Pipefile, and Django 1.11 doesn't support Python 3.7.
I ended up using Nix to be able to use python 3.7 everywhere, except in our projects. I added a shell.nix file ([instructions here](https://github.com/mozilla/network-pulse-api#nix-shell) if your curious) but I wouldn't go in that direction if you're not familiar with Nix or ready to handle weird, but super interesting, python corner cases. There's also pyenv to switch which version of python you're using, and [even automatically](https://pipenv.readthedocs.io/en/latest/advanced/#automatic-python-installation) with pyenv+pipenv, but I'm not familiar with it.

I'm closing this issue because inv and pipenv are not broken per se, but I can answer more questions if you want.

**Comment by gideonthomas** [comment]
perfect, this was helpful, thanks @patjouk!
