### ISSUE TITLE
Dockerize foundation.mozilla.org

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#665]
* [x] Meet and plan transition to Dockerized development and deploys
* [ ] https://github.com/MozillaFoundation/Docker-foundation-site/projects/1

**Comment by patjouk** [comment]
Closing this issue for now. Connected PR https://github.com/mozilla/foundation.mozilla.org/pull/3092

The first run on Travis is way too slow (15min) because we need to build everything and couldn't find a way to add a cache for dependencies. Run time after were around 8min, so slightly better than what we have now. It would have been okay if we were planning to use those images later on, but we can't because we also have to build on Heroku if we want to keep review apps.

In the end, it would have brought more complexity and slowness, without the benefit of running Docker.

If Heroku support for Heroku is getting better in the future, we might revisit the idea of using Docker on the Foundation site for testing and prod.

We will continue to work on supporting Docker for local dev because of the benefits it offers around cross-plateform.
