### ISSUE TITLE
Can we set up SQS for review apps Foundation?

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#695]
@alanmoo Can you remind me where we use SQS on the foundation site. Is it for the newsletter signup?

**Comment by alanmoo** [comment]
Petitions was the main reason for it. I believe signups also rely on it since we had it in place already (this goes for the footer of the site and in-page signups on BanneredCampaignPages). Both inherit from the CTA class (or something like that, this is off the top of my head. If you need more specifics, just ask)

**Comment by patjouk** [comment]
That's enough context, thanks :)

**Comment by patjouk** [comment]
Do we still want this?

**Comment by alanmoo** [comment]
No, I think our time would be better spent actually removing the SQS entirely for petitions/signups and just having a basket env var, with HTTP directly to Basket.
