### ISSUE TITLE
Update Mozfest Slack Pulse bot

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#703]
The Mozfest Slack #general is a bit noisy with Pulse entries. The Mozfest team has asked for it to be filtered to the same set of entries that appear on the MozFest site. It seems @patjouk created the integration, and is the only one who can modify it. The API query we want to use going forward (pulled from the MozFest site) is this (though it probably takes a different form for Slack).

https://api.mozillapulse.org/api/pulse/v2/entries/?format=json&help_type=Join%20community&page_size=6&search=mozfest-2019%20bloggrid&ordering=-created

**Comment by patjouk** [comment]
This zap is accessible to everyone who has access to the devops zapier account. It's called `(Mozfest - general) Latest from Pulse Slack Bot`

Right now, this zap is using the RSS feature from zapier, with the `latest from pulse` RSS feed (https://api.mozillapulse.org/rss/latest). The quick fix I can do for now is to use https://api.mozillapulse.org/rss/featured instead. It's less noisy because it's only publishing featured posts. If you want to compare, you can look at `mofo-featured-pulse` (`featured` feed) and `mozilla-pulse` (`latest` feed) in the Mozilla slack.

If it's not enough, I will have to investigate how to connect pulse to zapier.

**Comment by alanmoo** [comment]
The quick fix sounds like the right level of effort for this.

**Comment by patjouk** [comment]
done
