### ISSUE TITLE
Dependabot update - switch to monthly?

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#743]
We're lagging a bit behind, maybe it's time to consider moving dependabot to monthly updates instead of weekly ones. We would still get GitHub notifications for security updates and it will be easy to open them from there.

Opinions @cadecairos @Pomax @mmmavis

**Comment by Pomax** [comment]
I don't think the issue is so much that it's frequent, but that there's single PRs for every single thing that got updated, and every PR that is reviewed good then invalidates every other PR. Doing that monthly would probably still be a very long time of pressing merge, waiting for CI to pass on the next item, pressing merge again, and all the while other people can't really land code because each merge invalidates their PRs as well. It might be a good idea to have a look at whether there's a way to have dependabot PRs that pass CI get auto-aggregated (that might be something we have to request over on the dependabot issue tracker), so that 10 PRs that all update things that don't affect each other can be landed as a single PR without blocking everyone's ability to get "real" changes landed.

**Comment by mmmavis** [comment]
Agreed with what @Pomax said. 

Also wondering if we could adjust the frequency from weekly to bi-weekly for the time being.

**Comment by cadecairos** [comment]
Doing updates individually is something we probably want to keep, since it can surface issues related to a specific change. 

The real issue we have is that piplock files are implemented foolishly and constantly cause merge issues when software unrelated to the actuall version bump get incremented (looking at _you_ boto3)

**Comment by Pomax** [comment]
That's part 2 of the real issue,but from a dev side, the real issue is that it takes an hour, easy, to merge 10 dependabot PRs because of CI reruns and time lost by "everyone else not doing dependabot PRs" because their "green" PRs keep turning "out of date", too.

**Comment by patjouk** [comment]
Let's see how mergify is helping. If dependabot is still eating too much of our time, I'll reopen this ticket and investigate again.
